# Stage 1: Build the application
FROM node:21 AS builder
WORKDIR /app
COPY ./backend/package*.json ./
RUN npm ci
COPY backend .
RUN npm run compile

# Stage 2: Run the application
FROM node:21-slim
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY ./backend/package*.json ./

USER root
RUN chmod -R 775 /app
RUN npm install --omit=dev
EXPOSE 8001

CMD ["npm", "run", "start"]
#RUN node dist/app.js