version: '3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: db_ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
    ports:
      - "3306:3306"
  backend:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - database
  frontend:
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file: ./frontend/.env
    ports:
      - "8080:80"