#Stage 1
FROM node:21 AS builder
WORKDIR /app
COPY ./frontend .
RUN npm install
RUN npm run build

#Stage 2
FROM nginx:1.19.0

COPY nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .
ENTRYPOINT ["nginx", "-g", "daemon off;"]